version: '3.9'
services:
  backend-app:
    container_name: todo-backend
    build:
      dockerfile: local.Dockerfile
    command: '/app/scripts/docker/local-run.sh'
    ports:
      - '8080:8080'
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - './src:/app/src'

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - '${DB_HOST_PORT}:${DB_PORT}'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST=${DB_HOST}

volumes:
  data: